version: "3.8"
services:
  loopback:
    build:
        context: .
        dockerfile: enviroments/loopback/Dockerfile
    ports:
      - "3000:3000"

  rethinkdb:
    build:
      context: .
      dockerfile: enviroments/rethinkdb/Dockerfile
    ports:
      - "8080:8080"
