version: "3.8"
services:
  rethinkdb:
    image: rethinkdb
    ports:
     - "28015:28015"
    networks: 
      - rocket
    command: rethinkdb --bind all

  loopback:
    build: .
    ports:
      - "3000:3000"
    networks: 
      - rocket
  
      
networks:
  rocket:
    external: true 

  #0138f358f303f823a842cb06d9b5b68200ca055630ac1959bc669b97a462903a